name: Telegram Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설치 확인
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: requests 설치
        run: pip install requests

      - name: 봇 실행
        run: python bot.py
